### ISSUE TITLE
Scirius did not show any data on Suricata

### ISSUE THREAD

**Issue by maninivan** [StamusNetworks/scirius#111]
Hi! I'm using Scirius CE v1.2.2 And I ran into the problem of missing data on the home page https://selks/rules
Hostname сhecked.

**Comment by pevma** [comment]
Hi,
Thanks for trying it out!
Do you have data in the eve.json for the same period?

**Comment by maninivan** [comment]
Yes, there are data for this period.

**Comment by pevma** [comment]
Is the Scirius timezone correct as well ?

**Comment by maninivan** [comment]
Yes, correct.

**Comment by pevma** [comment]
Any relevant errs in the logs (Scirius/ES/Logstash)?

**Comment by maninivan** [comment]
scirius.log and scirius-error.log is empty
logtash.err.1:
May 25, 2017 7:53:20 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://127.0.0.1:9200: Broken pipe (Write failed)
May 25, 2017 7:53:20 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:9200
logtash-plain.log
[2017-06-05T10:01:58,005][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreachable or down? {:error_message=>"No Available connections", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError", :will_retry_in_seconds=>8}
[2017-06-05T10:01:58,014][WARN ][logstash.outputs.elasticsearch] UNEXPECTED POOL ERROR {:e=>#<LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError: No Available connections>}
[2017-06-05T10:01:58,015][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreachable or down? {:error_message=>"No Available connections", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError", :will_retry_in_seconds=>8}
[2017-06-05T10:01:58,017][WARN ][logstash.outputs.elasticsearch] UNEXPECTED POOL ERROR {:e=>#<LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError: No Available connections>}
[2017-06-05T10:01:58,017][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreachable or down? {:error_message=>"No Available connections", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError", :will_retry_in_seconds=>8}
[2017-06-05T10:01:58,060][WARN ][logstash.outputs.elasticsearch] UNEXPECTED POOL ERROR {:e=>#<LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError: No Available connections>}
[2017-06-05T10:01:58,060][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreachable or down? {:error_message=>"No Available connections", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError", :will_retry_in_seconds=>8}
[2017-06-05T10:01:58,867][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://127.0.0.1:9200/, :path=>"/"}
[2017-06-05T10:01:58,872][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://127.0.0.1:9200/, :path=>"/"}
[2017-06-05T10:01:58,872][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<URI::HTTP:0x659d35e0 URL:http://127.0.0.1:9200/>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://127.0.0.1:9200/][Manticore::SocketException] Connection refused (Connection refused)"}
[2017-06-05T10:01:58,882][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<URI::HTTP:0x5e21e4ac URL:http://127.0.0.1:9200/>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://127.0.0.1:9200/][Manticore::SocketException] Connection refused (Connection refused)"}
[2017-06-05T10:02:03,874][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://127.0.0.1:9200/, :path=>"/"}
[2017-06-05T10:02:03,885][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://127.0.0.1:9200/, :path=>"/"}
[2017-06-05T10:02:04,715][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>#<URI::HTTP:0x47cdab94 URL:http://127.0.0.1:9200/>}
[2017-06-05T10:02:04,715][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>#<URI::HTTP:0x372fac5c URL:http://127.0.0.1:9200/>}
elasticsearch.log
[2017-06-05T15:23:35,259][DEBUG][o.e.a.s.TransportSearchAction] [uy7OtMU] [logstash-alert-2017.06.04][3], node[uy7OtMUDSOODjjEephK93A], [P], s[STARTED], a[id=zgwzEttjQ5GGcpNFKxVu4A]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[logstash-alert-2017.06.04, logstash-alert-2017.06.05], indicesOptions=IndicesOptions[id=39, ignore_unavailable=true, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[], routing='null', preference='1496658012877', requestCache=null, scroll=null, source={
  "size" : 0,
  "query" : {
    "bool" : {
      "must" : [
        {
          "query_string" : {
            "query" : "event_type: alert",
            "fields" : [ ],
            "use_dis_max" : true,
            "tie_breaker" : 0.0,
            "default_operator" : "or",
            "auto_generate_phrase_queries" : false,
            "max_determinized_states" : 10000,
            "enable_position_increments" : true,
            "fuzziness" : "AUTO",
            "fuzzy_prefix_length" : 0,
            "fuzzy_max_expansions" : 50,
            "phrase_slop" : 0,
            "analyze_wildcard" : true,
            "escape" : false,
            "split_on_whitespace" : true,
            "boost" : 1.0
          }
        },
        {
          "match" : {
            "src_port" : {
              "query" : 18191,
              "type" : "phrase",
              "operator" : "OR",
              "prefix_length" : 0,
              "max_expansions" : 50,
              "fuzzy_transpositions" : true,
              "lenient" : false,
              "zero_terms_query" : "NONE",
              "boost" : 1.0
            }
          }
        },
        {
          "query_string" : {
            "query" : "*",
            "fields" : [ ],
            "use_dis_max" : true,
            "tie_breaker" : 0.0,
            "default_operator" : "or",
            "auto_generate_phrase_queries" : false,
            "max_determinized_states" : 10000,
            "enable_position_increments" : true,
            "fuzziness" : "AUTO",
            "fuzzy_prefix_length" : 0,
            "fuzzy_max_expansions" : 50,
            "phrase_slop" : 0,
            "analyze_wildcard" : true,
            "escape" : false,
            "split_on_whitespace" : true,
            "boost" : 1.0
          }
        },
        {
          "range" : {
            "@timestamp" : {
              "from" : 1496571815113,
              "to" : 1496658215113,
              "include_lower" : true,
              "include_upper" : true,
              "format" : "epoch_millis",
              "boost" : 1.0
            }
          }
        }
      ],
      "disable_coord" : false,
      "adjust_pure_negative" : true,
      "boost" : 1.0
    }
  },
  "version" : true,
  "_source" : {
    "includes" : [ ],
    "excludes" : [ ]
  },
  "aggregations" : {
    "2" : {
      "geohash_grid" : {
        "field" : "geoip.location",
        "precision" : 2,
        "size" : 10000
      },
      "aggregations" : {
        "3" : {
          "geo_centroid" : {
            "field" : "geoip.location"
          }
        }
      }
    }
  },
  "highlight" : {
    "pre_tags" : [
      "@kibana-highlighted-field@"
    ],
    "post_tags" : [
      "@/kibana-highlighted-field@"
    ],
    "fragment_size" : 2147483647,
    "fields" : {
      "*" : {
        "highlight_query" : {
          "bool" : {
            "must" : [
              {
                "query_string" : {
                  "query" : "event_type: alert",
                  "fields" : [ ],
                  "use_dis_max" : true,
                  "tie_breaker" : 0.0,
                  "default_operator" : "or",
                  "auto_generate_phrase_queries" : false,
                  "max_determinized_states" : 10000,
                  "enable_position_increments" : true,
                  "fuzziness" : "AUTO",
                  "fuzzy_prefix_length" : 0,
                  "fuzzy_max_expansions" : 50,
                  "phrase_slop" : 0,
                  "analyze_wildcard" : true,
                  "escape" : false,
                  "split_on_whitespace" : true,
                  "all_fields" : true,
                  "boost" : 1.0
                }
              },
              {
                "match" : {
                  "src_port" : {
                    "query" : 18191,
                    "type" : "phrase",
                    "operator" : "OR",
                    "prefix_length" : 0,
                    "max_expansions" : 50,
                    "fuzzy_transpositions" : true,
                    "lenient" : false,
                    "zero_terms_query" : "NONE",
                    "boost" : 1.0
                  }
                }
              },
              {
                "query_string" : {
                  "query" : "*",
                  "fields" : [ ],
                  "use_dis_max" : true,
                  "tie_breaker" : 0.0,
                  "default_operator" : "or",
                  "auto_generate_phrase_queries" : false,
                  "max_determinized_states" : 10000,
                  "enable_position_increments" : true,
                  "fuzziness" : "AUTO",
                  "fuzzy_prefix_length" : 0,
                  "fuzzy_max_expansions" : 50,
                  "phrase_slop" : 0,
                  "analyze_wildcard" : true,
                  "escape" : false,
                  "split_on_whitespace" : true,
                  "all_fields" : true,
                  "boost" : 1.0
                }
              },
              {
                "range" : {
                  "@timestamp" : {
                    "from" : 1496571815113,
                    "to" : 1496658215113,
                    "include_lower" : true,
                    "include_upper" : true,
                    "format" : "epoch_millis",
                    "boost" : 1.0
                  }
                }
              }
            ],
            "disable_coord" : false,
            "adjust_pure_negative" : true,
            "boost" : 1.0
          }
        }
      }
    }
  }
}}] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [uy7OtMU][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: java.lang.IllegalArgumentException: Expected geo_point type on field [geoip.location], but got [float]
	at org.elasticsearch.search.aggregations.support.ValuesSourceConfig.geoPointField(ValuesSourceConfig.java:341) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.search.aggregations.support.ValuesSourceConfig.originalValuesSource(ValuesSourceConfig.java:293) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.search.aggregations.support.ValuesSourceConfig.toValuesSource(ValuesSourceConfig.java:247) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:51) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:221) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.search.aggregations.AggregatorFactories.createTopLevelAggregators(AggregatorFactories.java:224) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.search.aggregations.AggregationPhase.preProcess(AggregationPhase.java:55) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:106) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.indices.IndicesService.lambda$loadIntoContext$16(IndicesService.java:1107) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.indices.IndicesService.lambda$cacheShardLevelResult$18(IndicesService.java:1188) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.indices.IndicesRequestCache$Loader.load(IndicesRequestCache.java:160) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.indices.IndicesRequestCache$Loader.load(IndicesRequestCache.java:143) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.common.cache.Cache.computeIfAbsent(Cache.java:398) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.indices.IndicesRequestCache.getOrCompute(IndicesRequestCache.java:116) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.indices.IndicesService.cacheShardLevelResult(IndicesService.java:1194) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.indices.IndicesService.loadIntoContext(IndicesService.java:1106) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:245) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:261) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:331) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:328) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:627) [elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.4.0.jar:5.4.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[2017-06-05T15:23:36,703][INFO ][o.e.m.j.JvmGcMonitorService] [uy7OtMU] [gc][19258] overhead, spent [273ms] collecting in the last [1s]

**Comment by pevma** [comment]
I cant reproduce this - but have seen it before.
Can you reproduce this every time? Does data get populated in any other dashboards (Kibana if you have them for example) for the same period ?

**Comment by maninivan** [comment]
Yes, I can reproduce this every time.  In the remaining panels for this period of time, all graphics and data are available.

**Comment by regit** [comment]
When opening the rules page, you should have an AJAX query which is made to `/rules/es?query=timeline&from_date=MORE_PARAMS`. Could you try to get the url and display its result here ?

**Comment by regit** [comment]
Second question, if you switch to 1h time range, do you see something ?

**Comment by maninivan** [comment]
https://xx.xx.xx.xx/rules/ruleset/1/

The switching of time intervals does not change anything.

**Comment by regit** [comment]
ok on time interval. Regarding the url, I wanted the url sending json to build the timeline. Url you gave me is one for a ruleset.

**Comment by regit** [comment]
@maninivan it seems you are using a custom scirius installation. What is the index containing alerts in Elasticsearch ?

**Comment by lukelee1987** [comment]
Hi can anyone provide me some support too. My Suricata in Scirius is not getting any data and unable to fetch to display. 
![scirius_nodata](https://user-images.githubusercontent.com/29053050/49554073-98fb7780-f935-11e8-8bae-c35328d68a8c.PNG)

But I can see some data from Kibana which I manually imported them.

**Comment by pevma** [comment]
@lukelee1987  - are you using 3.0.1 latest Scirius ? Also do you have `"event_type":"alert"` events in `/var/log/suricata/eve.json` ?
