### ISSUE TITLE
error with NPM

### ISSUE THREAD

**Issue by fratou77** [StamusNetworks/scirius#134]
Hello,

When I install the latest NPM version (sudo npm install -g npm@latest) and next I want to install webpack (sudo npm install -g  webpack@3.11), I this error :+1: 
**/usr/bin/env: node: No file or folder of this type**

To fix that, you have to create a symbolic link with the command sudo ln -s /usr/bin/nodejs /usr/bin/node but the nodejs-legacy package is supposed to solve the problem. 
And I tried both solutions but when I want to install the webpack, I get the same error :

/usr/local/lib/node_modules/npm/bin/npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
          ^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Anyone has found a solution for this problem please ?

**Comment by nkh8212** [comment]
https://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu

**Comment by basharabdullah** [comment]
@fratou77 have you managed to solve this problem?

**Comment by pevma** [comment]
I think the docs were also updated to refelct any changes needed.

**Comment by merkur0** [comment]
Also having this issue which makes me install Node again every time I reopen the terminal. Any way to fix this?

**Comment by atanasov-stoyan** [comment]
Hey @fratou77,
I think you have broken your npm. Take a look here how to recover it. Also please share your versions of npm and nodejs.

**Comment by stoyan-atanasoff** [comment]
Hey @fratou77,
I think you have broken your npm. Take a look here how to recover it. Also please share your versions of npm and nodejs.
