### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by Blisk** [StamusNetworks/scirius#136]
Can someone help me with installation on centos 7.4.
I am stuck here suricata.yaml I already have path to rules for suricata
default-rule-path: /etc/suricata/rules
rule-files:
 - scirius.rules

One possible way to do that is to use suri_reloader available in suricata/scripts directory. The syntax of suri_reloader can be something similar to

suri_reloader -p /path/to/rules  -l /var/log/suri-reload.log  -D

is a /path/to/rules to rules of suricata? /etc/suricata/rules
So where I can find suricata/scripts folder and where I get suri_reloader

**Comment by pevma** [comment]
Yes - path to rules. Is ``/usr/sbin/suri_reloader`` there ?

**Comment by Blisk** [comment]
no suri_reloader in this path /usr/sbin/suri_reloader
maybe I didn't install this as it should be?
I have followed this instructions https://scirius.readthedocs.io/en/latest/installation-ce.html

**Comment by Blisk** [comment]
any help, please?

**Comment by pevma** [comment]
> On 10 May 2018, at 09:40, Blisk <notifications@github.com> wrote:
> 
> any help, please?
> 


This is the script location on GitHub - 
https://github.com/StamusNetworks/scirius/tree/master/suricata/scripts

**Comment by Blisk** [comment]
I thought that is installed with setup?

**Comment by pevma** [comment]
It probably should - maybe it is installed in a different location ?

**Comment by FOX0809** [comment]
Hi, **suri_reloader** is locate in **/scirius/suricata/scripts** . I think you download scirius by 
$ git clone https://github.com/StamusNetworks/scirius , yes?
I think **/path/to/rules** is path of **/etc/suricata/rules/**, and **scirius.rules** must locate in **/etc/suricata/rules/**. Am I right?

**Comment by Blisk** [comment]
I still didn't manage to run this and as far as I see this project is almost dead.

**Comment by pevma** [comment]
You should have been able to run it - not sure how it doesn't work in your particular case.

The project is very much alive and widely used btw -  if you are interested for an easy try  -  you can download and spin up SELKS and have  a look - https://www.stamus-networks.com/open-source/  

Check out the docs as well if needed.
https://github.com/StamusNetworks/SELKS/wiki

**Comment by Blisk** [comment]
I follow this directions to install scirius on my centos 7 server, but nothing works
https://scirius.readthedocs.io/en/latest/installation-ce.html

I also see that SELKS works only on debian.

**Comment by pevma** [comment]
It should work under CentOS too.
So where are you stuck now? Do you have the web interface up and running yet? Are there any errors while you do the installation.

**Comment by Blisk** [comment]
First problem installing scirius is with installing npm. when I run 
sudo npm install -g npm@latest webpack@3.11

I get this error
```

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules/webpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 3.10.0-862.3.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "-g" "npm@latest" "webpack@3.11"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! path /usr/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map' -> '/usr/lib/node_modules/webpack/node_modules/concat-map'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map' -> '/usr/lib/node_modules/webpack/node_modules/concat-map'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /root/scirius/npm-debug.log
```

and this is from debug
```

47944 silly rollbackFailedOptional Starting
47945 silly rollbackFailedOptional Finishing
47946 silly runTopLevelLifecycles Finishing
47947 silly install printInstalled
47948 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules/webpack/node_modules/chokidar/node_modules/fsevents):
47949 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
47950 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
47950 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
47950 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
47950 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
47951 verbose stack Error: ENOENT: no such file or directory, rename '/usr/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map' -> '/usr/lib/node_modules/webpack/node_modules/concat-map'
47951 verbose stack     at /usr/lib/node_modules/npm/lib/install/action/move.js:86:7
47951 verbose stack     at /usr/lib/node_modules/npm/node_modules.bundled/iferr/index.js:11:16
47951 verbose stack     at /usr/lib/node_modules/npm/lib/utils/rename.js:11:14
47951 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
47951 verbose stack
47951 verbose stack Error: ENOENT: no such file or directory, rename '/usr/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map' -> '/usr/lib/node_modules/webpack/node_modules/concat-map'
47951 verbose stack     at Error (native)
47952 verbose cwd /root/scirius
47953 error Linux 3.10.0-862.3.2.el7.x86_64
47954 error argv "/usr/bin/node" "/bin/npm" "install" "-g" "npm@latest" "webpack@3.11"
47955 error node v6.14.2
47956 error npm  v3.10.10
47957 error path /usr/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map
47958 error code ENOENT
47959 error errno -2
47960 error syscall rename
47961 error enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map' -> '/usr/lib/node_modules/webpack/node_modules/concat-map'
47962 error enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map' -> '/usr/lib/node_modules/webpack/node_modules/concat-map'
47962 error enoent This is most likely not a problem with npm itself
47962 error enoent and is related to npm not being able to find a file.
47963 verbose exit [ -2, true ]
```

**Comment by pevma** [comment]
Seems CentOS specific - related to installation of npm/webpack - you can make be try a diff  web pack version or non install check.

> -- 
> Regards,
> Peter Manev

**Comment by Blisk** [comment]
What do you mean differend web pack? where I can get it?
Where I can get noninstallation version?

**Comment by pevma** [comment]
> On 21 Jun 2018, at 13:51, Blisk <notifications@github.com> wrote:
> 
> What do you mean differend web pack? where I can get it?
> Where I can get noninstallation version?
> 

For example - 
https://webpack.js.org/guides/installation/

**Comment by Blisk** [comment]
I manage to install something now but still have the same problem with suri_reloader, can not be found.
and this in web
![2018-06-21 14_03_01-localhost localdomainpovej net_1 root - tightvnc viewer](https://user-images.githubusercontent.com/2773050/41718120-4ea8014c-755c-11e8-9c32-621c17f87aa1.png)

**Comment by pevma** [comment]
Did you install webpack successfully (and run it after that)? It gives me an err on CentOS that i can not get past.

**Comment by Blisk** [comment]
I just checked no webpack doesn't work

**Comment by pevma** [comment]
Probably that is the first thing that needs to be fixed/installed properly.

**Comment by Blisk** [comment]
webpack now work, but it wants to install webpack-cli and that doesn't work

**Comment by FOX0809** [comment]
In documentation says what you must install v3.11 and you don't have this problem
