### ISSUE TITLE
Dashboards showing No dashboards

### ISSUE THREAD

**Issue by Eagleman7** [StamusNetworks/scirius#157]
This link works:
![image](https://user-images.githubusercontent.com/4787591/46862308-de5b6700-ce14-11e8-9be0-d5290293536d.png)

However it is not showing any of the dashboards I have (Imported with https://github.com/StamusNetworks/KTS6)
![image](https://user-images.githubusercontent.com/4787591/46862179-9f2d1600-ce14-11e8-9437-e1cbb3b8b235.png)

local_settings.py
```
import os

DBBACKUP_STORAGE = 'dbbackup.storage.filesystem_storage'
#DBBACKUP_STORAGE_OPTIONS = {'location': '/opt/scirius/backups/'}
DBBACKUP_STORAGE_OPTIONS = {'location': '/var/backups/'}

USE_ELASTICSEARCH = True
ELASTICSEARCH_ADDRESS = "192.168.1.45:9200"
ELASTICSEARCH_VERSION = 6
ELASTICSEARCH_KEYWORD = "keyword"
ELASTICSEARCH_LOGSTASH_ALERT_INDEX="logstash-alert-"


USE_KIBANA = True
KIBANA_URL = "http://monitoring.corp.pootenterprise.com:5601/"
KIBANA_VERSION=6

KIBANA_DASHBOARDS_PATH = "/opt/KTS6/"

USE_SURICATA_STATS = True
USE_LOGSTASH_STATS = True


SURICATA_NAME_IS_HOSTNAME = False
ALLOWED_HOSTS=["*"]


#ALLOWED_HOSTS = ["ips.corp.pootenterprise.com"]
```

**Comment by pevma** [comment]
You need to reset/load them. Did you try that? (From `System settings->Kibana-Reset Dashboards``)

**Comment by Eagleman7** [comment]
When I do that it shows me this:

```
Reset failed: TransportError(400, u'illegal_argument_exception', u'Rejecting mapping update to [.kibana] as the final mapping would have more than 1 type: [index-pattern, doc]')
```

./load.sh 192.168.1.45:9200 works however.

**Comment by pevma** [comment]
You need to specify the path to the first folder “dashboards” I think - in local_settings.py

> -- 
> Regards,
> Peter Manev

**Comment by pevma** [comment]
I think it needs to be 
“/opt/KTS6/dashboards/“

> -- 
> Regards,
> Peter Manev

**Comment by Eagleman7** [comment]
When change to that it shows:

```
Reset failed: Please make sure Kibana dashboards are installed at /opt/KTS6/dashboards/: no index-pattern found
```

**Comment by pevma** [comment]
So the folder you specified should have that content - (do “ls -lh /opt/KTS/dashboards/“ to confirm)
https://github.com/StamusNetworks/KTS6/tree/master/dashboards


> -- 
> Regards,
> Peter Manev

**Comment by Eagleman7** [comment]
```
[root@ips KTS]# ls -lh /opt/KTS/dashboards/
total 36K
drwxr-xr-x. 2 root root 4.0K Oct 13 09:35 dashboard
drwxr-xr-x. 2 root root 4.0K Oct 13 09:35 index-pattern
drwxr-xr-x. 2 root root 4.0K Oct 13 09:35 search
drwxr-xr-x. 2 root root  20K Oct 13 09:35 visualization
```

**Comment by Eagleman7** [comment]
Might be a bit confusing, but it is basicly all /opt/KTS on my end. changed it after uploading the config in the start post.

**Comment by Eagleman7** [comment]
Yes I have that.

**Comment by pevma** [comment]
If you do the following as root on the cmd - 
cd /usr/share/python/scirius/ && . bin/activate && python bin/manage.py kibana_reset && deactivate 


What would be the full output ?

> -- 
> Regards,
> Peter Manev

**Comment by Eagleman7** [comment]
```
[root@ips scirius]# cd /usr/share/python/scirius/ && . bin/activate && python bin/manage.py kibana_reset && deactivate
bash: cd: /usr/share/python/scirius/: No such file or directory
[root@ips scirius]# pwd
/opt/scirius
[root@ips scirius]# ls
accounts  backups  data  db.sqlite3  doc  git-sources  LICENSE  manage.py  MANIFEST.in  node_modules  npm  package.json  postcss.config.js  README.rst  requirements.txt  rules  scirius  scss  setup.py  suricata  tests  viz  webpack.config.js
[root@ips scirius]# python manage.py kibana_reset
/usr/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.16) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/scirius/rules/management/commands/kibana_reset.py", line 37, in handle
    self.kibana_reset()
  File "/opt/scirius/rules/es_data.py", line 235, in kibana_reset
    raise Exception('Please make sure Kibana dashboards are installed at %s: no index-pattern found' % settings.KIBANA_DASHBOARDS_PATH)
Exception: Please make sure Kibana dashboards are installed at /opt/KTS/dashboards/: no index-pattern found
```

**Comment by Eagleman7** [comment]
With /opt/KTS:

```
[root@ips scirius]# python manage.py kibana_reset
/usr/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.16) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/scirius/rules/management/commands/kibana_reset.py", line 37, in handle
    self.kibana_reset()
  File "/opt/scirius/rules/es_data.py", line 244, in kibana_reset
    self._kibana_inject(_type, _file)
  File "/opt/scirius/rules/es_data.py", line 159, in _kibana_inject
    self.client.create(index='.kibana', doc_type=_type, id=name, body=content, refresh=True)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 260, in create
    id, '_create'), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 161, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'illegal_argument_exception', u'Rejecting mapping update to [.kibana] as the final mapping would have more than 1 type: [index-pattern, doc]')
```

**Comment by pevma** [comment]
Is that on ES6 ?

> -- 
> Regards,
> Peter Manev

**Comment by Eagleman7** [comment]
This is elasticsearch 6, yes.

**Comment by pevma** [comment]
And this is the latest git pull of KTS6 correct ? (I did some updates on Friday - wanted to know if that may have some effect)

> -- 
> Regards,
> Peter Manev

**Comment by Eagleman7** [comment]
Latest version:

```
[root@ips KTS]# date
Sun Oct 14 10:37:37 CEST 2018
[root@ips KTS]# git pull
Already up-to-date.
[root@ips KTS]# cd ../scirius/
[root@ips scirius]# python manage.py kibana_reset
/usr/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.16) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/scirius/rules/management/commands/kibana_reset.py", line 37, in handle
    self.kibana_reset()
  File "/opt/scirius/rules/es_data.py", line 244, in kibana_reset
    self._kibana_inject(_type, _file)
  File "/opt/scirius/rules/es_data.py", line 159, in _kibana_inject
    self.client.create(index='.kibana', doc_type=_type, id=name, body=content, refresh=True)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 260, in create
    id, '_create'), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 161, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'illegal_argument_exception', u'Rejecting mapping update to [.kibana] as the final mapping would have more than 1 type: [index-pattern, doc]')
```

**Comment by Eagleman7** [comment]
Yes

````
[root@ips KTS]# ./load.sh 192.168.1.45:9200
++ dirname ./load.sh
+ cd .
+ '[' -z 192.168.1.45:9200 ']'
+ ELASTICSEARCH=192.168.1.45:9200
+ '[' -z '' ']'
+ CURL=curl
+ echo curl
curl
+ DIR=dashboards
+ echo 'Cleaning elasticsearch'\''s kibana data'
Cleaning elasticsearch's kibana data
+ curl -H 'Content-Type: application/json' -XDELETE 192.168.1.45:9200/.kibana/
{"acknowledged":true}+ curl -H 'Content-Type: application/json' -XPUT 192.168.1.45:9200/.kibana/ -d @kibana-mappings
{"acknowledged":true,"shards_acknowledged":true,"index":".kibana"}+ for file in '$DIR/index-pattern/*.json'
++ get_name dashboards/index-pattern/index-pattern:06e1e3c0-c1c7-11e8-9888-3f5bc9c31629.json
++ basename dashboards/index-pattern/index-pattern:06e1e3c0-c1c7-11e8-9888-3f5bc9c31629.json .json
++ sed -e 's/ /%20/g'
+ name=index-pattern:06e1e3c0-c1c7-11e8-9888-3f5bc9c31629
+ echo 'Loading index pattern index-pattern:06e1e3c0-c1c7-11e8-9888-3f5bc9c31629:'
Loading index pattern index-pattern:06e1e3c0-c1c7-11e8-9888-3f5bc9c31629:
+ curl -H 'Content-Type: application/json' -XPOST 192.168.1.45:9200/.kibana/doc/index-pattern:06e1e3c0-c1c7-11e8-9888-3f5bc9c31629 -d @dashboards/index-pattern/index-pattern:06e1e3c0-c1c7-11e8-9888-3f5bc9c31629.json
{"_index":".kibana","_type":"doc","_id":"index-pattern:06e1e3c0-c1c7-11e8-9888-3f5bc9c31629","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1}+ echo

+ for file in '$DIR/index-pattern/*.json'
++ get_name dashboards/index-pattern/index-pattern:35f3ece0-cae5-11e8-9f69-c36de0ada098.json
++ basename dashboards/index-pattern/index-pattern:35f3ece0-cae5-11e8-9f69-c36de0ada098.json .json
++ sed -e 's/ /%20/g'
+ name=index-pattern:35f3ece0-cae5-11e8-9f69-c36de0ada098
+ echo 'Loading index pattern index-pattern:35f3ece0-cae5-11e8-9f69-c36de0ada098:'
Loading index pattern index-pattern:35f3ece0-cae5-11e8-9f69-c36de0ada098:
+ curl -H 'Content-Type: application/json' -XPOST 192.168.1.45:9200/.kibana/doc/index-pattern:35f3ece0-cae5-11e8-9f69-c36de0ada098 -d @dashboards/index-pattern/index-pattern:35f3ece0-cae5-11e8-9f69-c36de0ada098.json
{"_index":".kibana","_type":"doc","_id":"index-pattern:35f3ece0-cae5-11e8-9f69-c36de0ada098","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":1,"_primary_term":1}+ echo

+ for file in '$DIR/index-pattern/*.json'
++ get_name dashboards/index-pattern/index-pattern:769209d0-c18a-11e8-9888-3f5bc9c31629.json
++ basename dashboards/index-pattern/index-pattern:769209d0-c18a-11e8-9888-3f5bc9c31629.json .json
++ sed -e 's/ /%20/g'
+ name=index-pattern:769209d0-c18a-11e8-9888-3f5bc9c31629
+ echo 'Loading index pattern index-pattern:769209d0-c18a-11e8-9888-3f5bc9c31629:'
Loading index pattern index-pattern:769209d0-c18a-11e8-9888-3f5bc9c31629:
+ curl -H 'Content-Type: application/json' -XPOST 192.168.1.45:9200/.kibana/doc/index-pattern:769209d0-c18a-11e8-9888-3f5bc9c31629 -d @dashboards/index-pattern/index-pattern:769209d0-c18a-11e8-9888-3f5bc9c31629.json
{"_index":".kibana","_type":"doc","_id":"index-pattern:769209d0-c18a-11e8-9888-3f5bc9c31629","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":2,"_primary_term":1}+ echo

+ for file in '$DIR/index-pattern/*.json'
++ get_name dashboards/index-pattern/index-pattern:770c39b0-c1c8-11e8-9888-3f5bc9c31629.json
++ basename dashboards/index-pattern/index-pattern:770c39b0-c1c8-11e8-9888-3f5bc9c31629.json .json
++ sed -e 's/ /%20/g'
+ name=index-pattern:770c39b0-c1c8-11e8-9888-3f5bc9c31629
+ echo 'Loading index pattern index-pattern:770c39b0-c1c8-11e8-9888-3f5bc9c31629:'
Loading index pattern index-pattern:770c39b0-c1c8-11e8-9888-3f5bc9c31629:
+ curl -H 'Content-Type: application/json' -XPOST 192.168.1.45:9200/.kibana/doc/index-pattern:770c39b0-c1c8-11e8-9888-3f5bc9c31629 -d @dashboards/index-pattern/index-pattern:770c39b0-c1c8-11e8-9888-3f5bc9c31629.json
{"_index":".kibana","_type":"doc","_id":"index-pattern:770c39b0-c1c8-11e8-9888-3f5bc9c31629","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":3,"_primary_term":1}+ echo
....................................................................................
```

**Comment by pevma** [comment]
I just tried it out on SELKS5 preview test machine that i have in my ``/etc/scirius/local_settings.py`` - ``KIBANA_DASHBOARDS_PATH = "/opt/selks/kibana6-dashboards/"
`` - 
```
root@SELKS5v2:~# ls -lh /opt/selks/kibana6-dashboards/
total 52K
-rw-r--r-- 1 root root  35K Sep 27 10:12 LICENSE
-rwxr-xr-x 1 root root 1.9K Sep 28 05:11 README.rst
drwxr-xr-x 6 root root 4.0K Oct 14 07:22 dashboards
-rwxr-xr-x 1 root root 1.5K Sep 27 10:12 load.sh
drwxr-xr-x 2 root root 4.0K Oct 12 08:35 patches
root@SELKS5v2:~# cd /usr/share/python/scirius/ && . bin/activate && python bin/manage.py kibana_reset
Kibana dashboards reloaded successfully
(scirius)root@SELKS5v2:/usr/share/python/scirius# 

```
It works fine (Scirius 3.0.7 from the Stamus SELKS5 preview repos). Couple of things that i noticed:
- 1. If you have upgraded form ELK5 to ELK6 you may need to migrate Kibana like so as well -  https://github.com/StamusNetworks/SELKS/blob/SELKS5/scripts/SELKS4-SELKS5/SN-S4-S5-Upgrade.sh#L313 (the three commands in sequance).
- 2. If this is a brand new install in your ``/etc/scirius/local_settings.py`` you should use ``/opt/KTS/`` in your case.
- 3. This should work on your Scirius - unless it is an older version or there is a missmatch for some reason. To be 100% sure - what is the version/commit of Scirius   that you are using currently ? (is ti the latest git available ?)

**Comment by Eagleman7** [comment]
This is a brand new installation of the entire ELK stack, everything is version 6.

In /opt/scirius/scirius/local_settings.py I am using /opt/KTS/

I am using version scirius-2.0.1 and commit fc0a005

**Comment by pevma** [comment]
@Eagleman7  - can you try to update/re pull and test it out.
Thanks @regit for the sync and upload !

**Comment by Eagleman7** [comment]
@pevma, are we talking about commit fdf54914d1b42e511afcb59d2390f2ba3e5c7def ?

I tried pulling the entire master branch before, but there are still some bugs, so I am waiting for the release.

**Comment by pevma** [comment]
You should be good with the latest master - https://github.com/StamusNetworks/scirius/commit/f7d891488fd77748dfe13610ed53c1b0712ecaec  . You can have  a look here - https://github.com/StamusNetworks/scirius/commits/master
