### ISSUE TITLE
add package requirement

### ISSUE THREAD

**Issue by AtzeDeVries** [StamusNetworks/scirius#19]
python-dev is a required package but is not noted on the website.

**Comment by regit** [comment]
Hello @AtzeDeVries , can you detail, I don't understand why it could be necessary ?

**Comment by AtzeDeVries** [comment]
This installation OS is Ubuntu 14.04 LTS Server

During install of the python module (via pip) of psutil this error is generated.

```
running build_ext

building '_psutil_linux' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/psutil

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_VERSION=221 -I/usr/include/python2.7 -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_linux.o

psutil/_psutil_linux.c:12:20: fatal error: Python.h: No such file or directory

 #include <Python.h>

                    ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-vf4uQE-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/psutil
Storing debug log for failure in /home/atze.devries/.pip/pip.log
1 root@suricata-sciriuis-development-001 /opt #  
```
Installing the package python-dev seems to fix is issue.

Also when running
```
python manage.py syncdb
```

I get this error
```
root@suricata-sciriuis-development-001 /opt/scirius (git)-[master] # python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/scirius/rules/models.py", line 33, in <module>
    import git
  File "/usr/local/lib/python2.7/dist-packages/git/__init__.py", line 29, in <module>
    _init_externals()
  File "/usr/local/lib/python2.7/dist-packages/git/__init__.py", line 23, in _init_externals
    raise ImportError("'gitdb' could not be found in your PYTHONPATH")
ImportError: 'gitdb' could not be found in your PYTHONPATH
```
running
```
pip install gitdb fixes this
```
then still running 
```
python manage.py syncdb
```
this error is generated
```
 root@suricata-sciriuis-development-001 /opt/scirius (git)-[master] # python manage.py pytz                             :(
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/scirius/accounts/models.py", line 23, in <module>
    import pytz
ImportError: No module named pytz
```

installing the python module pytz fixes this problem. After that everything seems to be running fine!

**Comment by regit** [comment]
Hi @AtzeDeVries 

Thanks a lot for this great and detailed report. I will update the README really soon.
