### ISSUE TITLE
Scirius backup at SELKS 5.0

### ISSUE THREAD

**Issue by VN1977** [StamusNetworks/scirius#191]
Hello!
I try to backup scirius and migrate to another host.
But if I start `python manage.py scbackup` I get error thet file manage.py not found.
This file is located at /usr/share/python/scirius/bin. 
After start `python manage.py scbackup` from that path I get
```
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
```

**Comment by pevma** [comment]
I think you would need to try with activating it first - 
```
cd /usr/share/python/scirius/ && . bin/activate && python bin/manage.py .....
```

**Comment by VN1977** [comment]
It works.
I made backup I decided to view list of all backups with command `python manage.py listbackups`
This command sends the errors.
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 206, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/dbbackup/management/commands/listbackups.py", line 8, in <module>
    from ._base import BaseDbBackupCommand
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/dbbackup/management/commands/_base.py", line 9, in <module>
    class BaseDbBackupCommand(LabelCommand):
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/dbbackup/management/commands/_base.py", line 13, in BaseDbBackupCommand
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```

**Comment by pevma** [comment]
That probably is a separate bug. What is your Scirius version ?

**Comment by VN1977** [comment]
I have the last version 3.2

**Comment by pevma** [comment]
If you make one more back up and repeat the list command - would the result be the same ?

**Comment by VN1977** [comment]
I have made three backups and have the same problem with viewing list.

**Comment by pevma** [comment]
ok - this is a bug then, we should be able to list them.
You do have the 3 backups though in the folder, right?

**Comment by VN1977** [comment]
Exactly three backups.

**Comment by xkill** [comment]
Hi, same problem:

I installed SELKS yesterday based on the latest version. Upgraded all the packages and rebooted.
Today I made a backup following the instructions at https://scirius.readthedocs.io/en/latest/backup-ce.html, but:

```
# /usr/share/python/scirius/bin/manage.py  listbackups
Traceback (most recent call last):
  File "/usr/share/python/scirius/bin/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 206, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/dbbackup/management/commands/listbackups.py", line 8, in <module>
    from ._base import BaseDbBackupCommand
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/dbbackup/management/commands/_base.py", line 9, in <module>
    class BaseDbBackupCommand(LabelCommand):
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/dbbackup/management/commands/_base.py", line 13, in BaseDbBackupCommand
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```
It could a problem with the django `listbackups` command, as `scbackup` is a *custom* command and not a django command. So, scirious should implement a sclistbackups command or remove this option from the documentation and the only way to list the backups is `ls -ltr /var/backups/db-scirius-*`
