### ISSUE TITLE
python manage.py migrate

### ISSUE THREAD

**Issue by willjjohnson1** [StamusNetworks/scirius#192]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/lib/python2.7/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/lib/python2.7/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib64/python2.7/logging/config.py", line 803, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib64/python2.7/logging/config.py", line 585, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler u'elasticsearch': [Errno 2] No such file or directory: u'/var/log/scirius/elasticsearch.log'

**Comment by willjjohnson1** [comment]
So after looking further back at my console logs I discovered like an idiot I had ignored a ton of peer dependencies.

After spending quite a lot of time since posting this issue on acquiring those peer dependencies, I have now discovered the issue is even better (worse) than I imagined.

Inside of scirius/hunt I have been installing all the required peer dependencies.
![image](https://user-images.githubusercontent.com/11711461/66776670-ec631e00-ee94-11e9-910d-8f5a1ae1f2c0.png)
react and react-dom both have versions installed greater than 16.3.0
and webpack has version 3.11.0 installed..
But as you can see I have modules requesting different versions of each.
Now if I ignore this entirely and run 'npm run build'
![image](https://user-images.githubusercontent.com/11711461/66776827-554a9600-ee95-11e9-937a-d444c8580221.png)
I am greated with this lovely error output.

**Comment by willjjohnson1** [comment]
When I try 'npm start' or 'npm test':
![image](https://user-images.githubusercontent.com/11711461/66777352-d22a3f80-ee96-11e9-99b5-a3f05f5dd04a.png)

**Comment by biolds** [comment]
What's your setup ? What documentation did you follow to reach that ?

**Comment by willjjohnson1** [comment]
Running CentOS 7 minimal on ESXi.
I started out following the documentation here: 
https://scirius.readthedocs.io/en/latest/installation-ce.html#running-scirius-ce
obviously adjusting for the difference between apt-get and yum
I also used:
https://linuxize.com/post/how-to-install-node-js-on-centos-7/#1-install-nvm-node-version-manager
For installing nvm, node, and npm
and:
https://www.cyberciti.biz/faq/centos-linux-install-gcc-c-c-compiler/
To make sure I had all the Development Tools.
and:
https://codeforgeek.com/make-failed-with-exit-code-2/
For fixing an error I had with exit code 2

**Comment by willjjohnson1** [comment]
My issue is the same as #186 
However when I run 'npm install' or 'npm run build' with sudo like josass did to resolve his issue, I get this error:

![image](https://user-images.githubusercontent.com/11711461/66843917-6f3eb400-ef3b-11e9-9252-96eb8267f719.png)

**Comment by willjjohnson1** [comment]
Solved by switching to Ubuntu 18.04. 
I am still attempting to get this working on CentOS 7 however..
