### ISSUE TITLE
Unable to configure handler u'elasticsearch'

### ISSUE THREAD

**Issue by datkps17** [StamusNetworks/scirius#193]
Hello everyone!
when i run _python manage.py migrate_ 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/administrator/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/administrator/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/administrator/.local/lib/python2.7/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/administrator/.local/lib/python2.7/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler u'elasticsearch': [Errno 2] No such file or directory: u'/var/log/scirius/elasticsearch.log'
How to fix it. Help me

**Comment by regit** [comment]
You need to have `/var/log/scirius/` created and to be able to write in it as the user running the migrate command.

Alternatively you can overwrite LOGGING variable in scirius/local_settings.py (from the one in scirius/settings.py)

**Comment by datkps17** [comment]
> You need to have `/var/log/scirius/` created and to be able to write in it as the user running the migrate command.
> 
> Alternatively you can overwrite LOGGING variable in scirius/local_settings.py (from the one in scirius/settings.py)

it works ! 
Thank you so much!
