### ISSUE TITLE
First start issue

### ISSUE THREAD

**Issue by JetDanTe** [StamusNetworks/scirius#237]
After install .iso on VM I were started first start and selks upgrade commands.
They were executed success but scirius was stopped.
When I start to rerun first start I will get new error:
`Added
Traceback (most recent call last):
  File "bin/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/python/scirius/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/scirius/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/scirius/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/scirius/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/scirius/lib/python3.7/site-packages/rules/management/commands/kibana_reset.py", line 34, in handle
    self.kibana_reset()
  File "/usr/share/python/scirius/lib/python3.7/site-packages/rules/es_data.py", line 1981, in kibana_reset
    if not os.path.isdir(self._get_dashboard_dir()):
  File "/usr/share/python/scirius/lib/python3.7/site-packages/rules/es_data.py", line 1909, in _get_dashboard_dir
    kibana7_path = getattr(settings, 'KIBANA7_DASHBOARDS_PATH')
  File "/usr/share/python/scirius/lib/python3.7/site-packages/django/conf/__init__.py", line 80, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'KIBANA7_DASHBOARDS_PATH'
Dashboards loading set up job failed...Exiting...
### Exited with ERROR  ###`

'KIBANA7_DASHBOARDS_PATH' var exist in settings.py

**Comment by pevma** [comment]
Hi,

Are you using the SELKS iso?
Just checking if you did you do the first time setup - https://github.com/StamusNetworks/SELKS/wiki/First-time-setup 

Thank you

**Comment by JetDanTe** [comment]
In my post below I wrote **_After install .iso on VM I were started first start and selks upgrade commands._**
It`s mean I already start fisrt time script and get some errors. After read github issues  I try to start first time again.

**Comment by pevma** [comment]
Can you enable the test repo and retry 
```
cat /etc/apt/sources.list.d/selks6.list 

deb http://packages.stamus-networks.com/selks6/debian/ buster main
deb http://packages.stamus-networks.com/selks6/debian-kernel/ buster main
deb http://packages.stamus-networks.com/selks6/debian-test/ buster main
```
Would that make things better ?

**Comment by JetDanTe** [comment]
Nope. Test repo enabled already.

**Comment by pevma** [comment]
Do you have enough resources for the VM as per the minimum requirements?   
You first need to run the setup command, that automatically invokes any upgrades if needed  -is that the case?
One more question - you have not done any manual edits to the scirius config - just following the wiki correct?
