### ISSUE TITLE
Failed to minify the code from this file: ./node_modules/patternfly-react/dist/esm/common/helpers.js:14

### ISSUE THREAD

**Issue by da667** [StamusNetworks/scirius#252]
Hello,

Trying to install scirius-ce from source on ubuntu 21.04 LTS. I'm following the documentation on:
https://scirius.readthedocs.io/en/latest/installation-ce.html

the problem I'm running into is running the command `npm run build` in the `./scirius/hunt`  directory. Half the time I get a stack trace of errors that seems to indicate that a js file is missing:

```
~/scirius/hunt# npm run build

> hunt@0.1.0 build /root/scirius/hunt
> npm run copy-fonts && npm run copy-img && npm run build-css && npm run build-js


> hunt@0.1.0 copy-fonts /root/scirius/hunt
> mkdir -p src/fonts && cp node_modules/patternfly/dist/fonts/* src/fonts


> hunt@0.1.0 copy-img /root/scirius/hunt
> cp node_modules/patternfly/dist/img/* src/img


> hunt@0.1.0 build-css /root/scirius/hunt
> node-sass-chokidar --importer=node_modules/node-sass-tilde-importer --include-path ./src --include-path ./node_modules --include-path ./node_modules/patternfly/node_modules/ --include-path=node_modules/patternfly/dist/sass/ --include-path=node_modules/bootstrap-sass/assets/stylesheets/ --include-path=node_modules/font-awesome-sass/assets/stylesheets/ --include-path=node_modules/react-grid-layout/css/ --include-path=node_modules/react-resizable/css/ --include-path=node_modules/patternfly-react/dist/sass/ src/ -o src/css/ && node-sass-chokidar ./src/css/containers/App/App.css -o ./src/css

Rendering Complete, saving .css file...
Wrote CSS to /root/scirius/hunt/src/css/containers/App/App.css
Wrote 1 CSS files to /root/scirius/hunt/src/css/
Rendering Complete, saving .css file...
Wrote CSS to /root/scirius/hunt/src/css/App.css

> hunt@0.1.0 build-js /root/scirius/hunt
> node scripts/build.js

Creating an optimized production build...
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/root/scirius/rules/static/bundles/service-worker.js'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at fileNames.filter.reduce (/root/scirius/hunt/node_modules/react-dev-utils/FileSizeReporter.js:132:31)
    at Array.reduce (<anonymous>)
    at recursive (/root/scirius/hunt/node_modules/react-dev-utils/FileSizeReporter.js:131:12)
    at /root/scirius/hunt/node_modules/recursive-readdir/index.js:81:22
    at /root/scirius/hunt/node_modules/recursive-readdir/index.js:88:20
    at FSReqWrap.oncomplete (fs.js:154:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hunt@0.1.0 build-js: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hunt@0.1.0 build-js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-19T19_33_32_675Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hunt@0.1.0 build: `npm run copy-fonts && npm run copy-img && npm run build-css && npm run build-js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hunt@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-19T19_33_32_880Z-debug.log
```

and the other half of the time I get this:

```
~/scirius/hunt# npm run build

> hunt@0.1.0 build /root/scirius/hunt
> npm run copy-fonts && npm run copy-img && npm run build-css && npm run build-js


> hunt@0.1.0 copy-fonts /root/scirius/hunt
> mkdir -p src/fonts && cp node_modules/patternfly/dist/fonts/* src/fonts


> hunt@0.1.0 copy-img /root/scirius/hunt
> cp node_modules/patternfly/dist/img/* src/img


> hunt@0.1.0 build-css /root/scirius/hunt
> node-sass-chokidar --importer=node_modules/node-sass-tilde-importer --include-path ./src --include-path ./node_modules --include-path ./node_modules/patternfly/node_modules/ --include-path=node_modules/patternfly/dist/sass/ --include-path=node_modules/bootstrap-sass/assets/stylesheets/ --include-path=node_modules/font-awesome-sass/assets/stylesheets/ --include-path=node_modules/react-grid-layout/css/ --include-path=node_modules/react-resizable/css/ --include-path=node_modules/patternfly-react/dist/sass/ src/ -o src/css/ && node-sass-chokidar ./src/css/containers/App/App.css -o ./src/css

Rendering Complete, saving .css file...
Wrote CSS to /root/scirius/hunt/src/css/containers/App/App.css
Wrote 1 CSS files to /root/scirius/hunt/src/css/
Rendering Complete, saving .css file...
Wrote CSS to /root/scirius/hunt/src/css/App.css

> hunt@0.1.0 build-js /root/scirius/hunt
> node scripts/build.js

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/patternfly-react/dist/esm/common/helpers.js:14

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hunt@0.1.0 build-js: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hunt@0.1.0 build-js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-19T19_36_41_882Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hunt@0.1.0 build: `npm run copy-fonts && npm run copy-img && npm run build-css && npm run build-js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hunt@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-19T19_36_41_943Z-debug.log
```

I'm following the documentation on read the docs to the letter, but this is where I'm stuck. I have no idea how to troubleshoot this, so any help would be appreciated so that I can get scirius running on my system.

**Comment by da667** [comment]
Okay. after a lot of grumbling, I figured out the problem. I think? I don't know. I'm not good at node.js.

Ubuntu 20.04's version of node.js is 10.19. I ended up installing nvm (node version manager) and installed the lts/dubnium release (10.24.1). I followed the read the docs info and it appeared to work, So... I'm going to close this ticket and chalk it up to being a node noob.
