### ISSUE TITLE
Unable to check ruleset validity

### ISSUE THREAD

**Issue by Drewshg312** [StamusNetworks/scirius#52]
Transfering issue from here: https://github.com/StamusNetworks/scirius/issues/51
So getting this:

![34621e0c-4ced-11e5-9baa-d69a015f6e9d](https://cloud.githubusercontent.com/assets/10493450/9565110/f2c1a334-4e70-11e5-8fea-714326d2b2fa.jpg)

and you saying:

"Ruleset has errors: is Suricata in the binary path of Scirius? Scirius needs to be able to start suricata in testing mode to check validity. You can test this by going to a single rule page, it will display the validity of the rule using the same testing mechanism. If it fails the same way then this should be the mistake."

I've created single rule page and got the same error. My Siricata is still red because of this issue:
https://github.com/StamusNetworks/scirius/issues/26 :
"There is a bug in suricata when working with BSD-flavored operation systems... Getting Unable to change permission on socket: Invalid argument (22) -- https://redmine.openinfosecfoundation.org/issues/1353
So waiting for fix from openinfo..."

and I still don't have suri reloader rewritten for osx so my scirius is basically doesn't have direct connection with my suricata… I hope to fix it in the future… but I was still able to create my scirius.rules file and manually restart suricata and all worked great.

"Ruleset has errors: is Suricata in the binary path of Scirius?" What do you mean? how can I check this?

**Comment by regit** [comment]
Scirius is now running suricata in test mode to check validity of rulesets.

I've just pushed to git a fix https://github.com/StamusNetworks/scirius/commit/fcca67d12dae456cf039eae6c194b71408d71a62 to permit user to specify the path to suricata binary in local_settings.py. Try to use the SURICATA_BINARY variable to allow scirius to start suricata in test mode.

**Comment by Drewshg312** [comment]
After `$ git pull`:
```
$ python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: staticfiles, messages, django_tables2, bootstrap3
  Apply all migrations: sessions, admin, suricata, auth, rules, contenttypes, accounts
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying accounts.0001_initial...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 316, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: table "accounts_sciriususer" already exists

Then:
```
$ /usr/local/bin/python /usr/local/var/www/scirius/manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

August 30, 2015 - 16:45:41
Django version 1.8.4, using settings 'scirius.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[30/Aug/2015 16:45:53] "GET /rules/info?query=disk HTTP/1.1" 200 48
[30/Aug/2015 16:45:53] "GET /rules/info?query=memory HTTP/1.1" 200 95
[30/Aug/2015 16:45:53] "GET /rules/es?query=health HTTP/1.1" 200 349
[30/Aug/2015 16:45:53] "GET /rules/info?query=status HTTP/1.1" 200 18

Why?

**Comment by regit** [comment]
Hi,

Run:
```
python manage.py migrate accounts --fake 0001_initial
```
To fix the migration issue.

**Comment by Drewshg312** [comment]
```
$ python manage.py migrate accounts --fake 0001_initial
usage: manage.py migrate [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS]
                         [--pythonpath PYTHONPATH] [--traceback] [--no-color]
                         [--noinput] [--no-initial-data] [--database DATABASE]
                         [--fake] [--fake-initial] [--list]
                         [app_label] [migration_name]
manage.py migrate: error: unrecognized arguments: 0001_initial

**Comment by regit** [comment]
Try to put fake just after migrate.

**Comment by Drewshg312** [comment]
$ python manage.py migrate --fake accounts 0001_initial
Operations to perform:
  Target specific migration: 0001_initial, from accounts
Running migrations:
  Rendering model states... DONE
  Applying accounts.0001_initial... FAKED

$ /usr/local/bin/python /usr/local/var/www/scirius/manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

August 30, 2015 - 17:39:33
Django version 1.8.4, using settings 'scirius.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```
It's still there(((

**Comment by regit** [comment]
retry the migrate command :)

**Comment by Drewshg312** [comment]
it didn't help. So I've retried with --fake and got:
```
$ python manage.py migrate --fake accounts 0001_initial
Operations to perform:
  Target specific migration: 0001_initial, from accounts
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

**Comment by regit** [comment]
What is the output of
```
python manage.py migrate
```
?

**Comment by Drewshg312** [comment]
```
$ python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: staticfiles, messages, django_tables2, bootstrap3
  Apply all migrations: sessions, admin, suricata, auth, rules, contenttypes, accounts
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying rules.0041_source_authkey... OK
  Applying suricata.0001_initial...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 316, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: table "suricata_suricata" already exists
```

**Comment by regit** [comment]
Run a fake on this one too :)
```
python manage.py migrate --fake suricata 0001_initial
```
or backup and run
```
python manage.py migrate --fake suricata
```

**Comment by Drewshg312** [comment]
```
$ python manage.py migrate --fake suricata 0001_initial
Operations to perform:
  Target specific migration: 0001_initial, from suricata
Running migrations:
  Rendering model states... DONE
  Applying suricata.0001_initial... FAKED

$ python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: staticfiles, messages, django_tables2, bootstrap3
  Apply all migrations: sessions, admin, suricata, auth, rules, contenttypes, accounts
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

**Comment by regit** [comment]
OK, it seems you have mad it :+1:

**Comment by Drewshg312** [comment]
Oh! You are right! Thanx very much, man!

**Comment by Drewshg312** [comment]
So what exactly should I try now with `SURICATA_BINARY`?

**Comment by regit** [comment]
Set it to the path on your system to suricata program/binary

**Comment by Drewshg312** [comment]
ok so now added `SURICATA_BINARY = "/usr/local/bin/suricata"` to my **local_settings.py**, restarted the daemon and tried to update again... Got this:

![1](https://cloud.githubusercontent.com/assets/10493450/9568713/5706f912-4f06-11e5-8e41-8948350b759b.jpg)

and

![2](https://cloud.githubusercontent.com/assets/10493450/9568714/5b819934-4f06-11e5-9dc3-6e6c034ae62a.jpg)

**Comment by regit** [comment]
Interesting, do you have something below "Ruleset has errors" ?

**Comment by Drewshg312** [comment]
and my system status still looks like this:
![3](https://cloud.githubusercontent.com/assets/10493450/9568726/07b6cff8-4f07-11e5-94cf-0ad1d2e24593.jpg)
I guess because of that unix socket issue... just saying…

**Comment by Drewshg312** [comment]
Nothing  below "Ruleset has errors"

**Comment by Drewshg312** [comment]
Wait! I've refreshed the page and got this:

![4](https://cloud.githubusercontent.com/assets/10493450/9568735/801509ba-4f07-11e5-8999-df1c29320d19.jpg)

**Comment by regit** [comment]
ok :) can you open URLOFRULESET/test and put here the result ?

**Comment by Drewshg312** [comment]
`{"status": false, "errors": {"message": "30/8/2015 -- 18:10:34 - <Error> - [ERRCODE: SC_ERR_ACTION_ORDER(3)] - action-order, the config didn't specify all of the actions. Please, use \"pass\",\"drop\",\"alert\",\"reject\". You have to specify all of them, without quotes and without capital letters\n"}, "rules_count": 26208}`

**Comment by regit** [comment]
ok, looks like you need a newer suricata for now (git version). Stamus is packaging it but for linux Debian.

**Comment by Drewshg312** [comment]
you mean Development 	2.1beta4 version? I'm now using Stable 	2.0.8 from homebrew…

**Comment by regit** [comment]
Yes, 2.1beta4 and even git for better result if possible.

**Comment by Drewshg312** [comment]
Will try 2.1beta4 first (it's packaged) and then if it doesn't work I will add head to homebrew

**Comment by Drewshg312** [comment]
So I've restarted suricata manually and got looooong output (github even didn't allowed me to paste it because it's more than 262144 characters).. lol Here is just a part of it:
```
$ sudo /usr/local/bin/suricata -c /usr/local/etc/suricata/suricata.yaml -i en2
Password:
30/8/2015 -- 11:25:42 - <Notice> - This is Suricata version 2.1beta4 RELEASE
30/8/2015 -- 11:25:42 - <Warning> - [ERRCODE: SC_ERR_MODBUS_CONFIG(241)] - no Modbus TCP config found, enabling Modbus detection on port 502.
30/8/2015 -- 11:25:42 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature "alert ( msg: "DNP3_BAD_CRC"; sid:1; gid:145; rev: 1; metadata: rule-type preproc; classtype:protocol-command-decode; )" from file /usr/local/etc/suricata/rules/scirius.rules at line 2
30/8/2015 -- 11:25:42 - <Error> - [ERRCODE: SC_ERR_RULE_KEYWORD_UNKNOWN(102)] - unknown rule keyword 'sd_pattern'.
30/8/2015 -- 11:25:42 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature "alert tcp $HOME_NET any -> $EXTERNAL_NET [80,20,25,143,110] (msg:"SENSITIVE-DATA Credit Card Numbers"; metadata:service http, service smtp, service ftp-data, service imap, service pop3; sd_pattern:2,credit_card; classtype:sdf; sid:2; gid:138; rev:1;)" from file /usr/local/etc/suricata/rules/scirius.rules at line 3
30/8/2015 -- 11:25:42 - <Error> - [ERRCODE: SC_ERR_RULE_KEYWORD_UNKNOWN(102)] - unknown rule keyword 'sd_pattern'.
30/8/2015 -- 11:25:42 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature "alert tcp $HOME_NET any -> $EXTERNAL_NET [80,20,25,143,110] (msg:"SENSITIVE-DATA U.S. Social Security Numbers (with dashes)"; metadata:service http, service smtp, service ftp-data, service imap, service pop3; sd_pattern:2,us_social; classtype:sdf; sid:3; gid:138; rev:1;)" from file /usr/local/etc/suricata/rules/scirius.rules at line 4
30/8/2015 -- 11:25:42 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature "alert ( msg: "DNP3_REASSEMBLY_BUFFER_CLEARED"; sid:4; gid:145; rev: 1; metadata: rule-type preproc; classtype:protocol-command-decode; )" from file /usr/local/etc/suricata/rules/scirius.rules at line 5
30/8/2015 -- 11:25:42 - <Error> - [ERRCODE: SC_ERR_RULE_KEYWORD_UNKNOWN(102)] - unknown rule keyword 'sd_pattern'.
.....
30/8/2015 -- 11:25:52 - <Warning> - [ERRCODE: SC_ERR_EVENT_ENGINE(210)] - signature sid:2018908 has an event var set.  The signature event var is given precedence over the threshold.conf one.  We'll change this in the future though.
30/8/2015 -- 11:25:52 - <Warning> - [ERRCODE: SC_ERR_EVENT_ENGINE(210)] - signature sid:2019876 has an event var set.  The signature event var is given precedence over the threshold.conf one.  We'll change this in the future though.
30/8/2015 -- 11:25:52 - <Warning> - [ERRCODE: SC_ERR_EVENT_ENGINE(210)] - signature sid:2020853 has an event var set.  The signature event var is given precedence over the threshold.conf one.  We'll change this in the future though.
30/8/2015 -- 11:25:52 - <Notice> - all 19 packet processing threads, 4 management threads initialized, engine started.
```

**Comment by Drewshg312** [comment]
I use only a single  **scirius.rules** rule file…

**Comment by regit** [comment]
Yes, there is a LOT of errors in VRT rules when loaded by suricata

**Comment by Drewshg312** [comment]
Oh Ic... Anyways it didn't fix the problem - same "Ruleset has errors . :" and "Validity: False" messages...

But the `URLOFRULESET/test` now is filled with those errors (and this is just a small part of it):

```
{"status": false, "errors": {"message": "30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert ( msg: \"DNP3_BAD_CRC\"; sid:1; gid:145; rev: 1; metadata: rule-type preproc; classtype:protocol-command-decode; )\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 2\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_RULE_KEYWORD_UNKNOWN(102)] - unknown rule keyword 'sd_pattern'.\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert tcp $HOME_NET any -> $EXTERNAL_NET [80,20,25,143,110] (msg:\"SENSITIVE-DATA Credit Card Numbers\"; metadata:service http, service smtp, service ftp-data, service imap, service pop3; sd_pattern:2,credit_card; classtype:sdf; sid:2; gid:138; rev:1;)\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 4\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_RULE_KEYWORD_UNKNOWN(102)] - unknown rule keyword 'sd_pattern'.\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert tcp $HOME_NET any -> $EXTERNAL_NET [80,20,25,143,110] (msg:\"SENSITIVE-DATA U.S. Social Security Numbers (with dashes)\"; metadata:service http, service smtp, service ftp-data, service imap, service pop3; sd_pattern:2,us_social; classtype:sdf; sid:3; gid:138; rev:1;)\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 6\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert ( msg: \"DNP3_REASSEMBLY_BUFFER_CLEARED\"; sid:4; gid:145; rev: 1; metadata: rule-type preproc; classtype:protocol-command-decode; )\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 8\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_RULE_KEYWORD_UNKNOWN(102)] - unknown rule keyword 'sd_pattern'.\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert tcp $HOME_NET any -> $EXTERNAL_NET [80,20,25,143,110] (msg:\"SENSITIVE-DATA Email Addresses\"; metadata:service http, service smtp, service ftp-data, service imap, service pop3; sd_pattern:20,email; classtype:sdf; sid:5; gid:138; rev:1;)\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 10\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_RULE_KEYWORD_UNKNOWN(102)] - unknown rule keyword 'sd_pattern'.\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert tcp $HOME_NET any -> $EXTERNAL_NET [80,20,25,143,110] (msg:\"SENSITIVE-DATA U.S. Phone Numbers\"; metadata:service http, service smtp, service ftp-data, service imap, service pop3; sd_pattern:20,(\\d{3}) ?\\d{3}-\\d{4}; classtype:sdf; sid:6; gid:138; rev:1;)\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 12\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert ( msg: \"HI_CLIENT_INVALID_TRUEIP\"; sid:23; gid: 119; rev: 1; metadata: rule-type preproc ; classtype:unknown; )\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 14\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert ( msg: \"HI_CLIENT_MULTIPLE_HOST_HDRS\"; sid:24; gid: 119; rev: 1; metadata: rule-type preproc ; classtype:unknown; )\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 16\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert ( msg: \"HI_CLIENT_LONG_HOSTNAME\"; sid:25; gid: 119; rev: 1; metadata: rule-type preproc ; classtype:unknown; )\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 18\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert ( msg: \"HI_CLIENT_EXCEEDS_SPACES\"; sid:26; gid: 119; rev: 1; metadata: rule-type preproc ; classtype:attempted-dos;reference:cve,2004-0942; )\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 20\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert ( msg: \"HI_CLIENT_UNESCAPED_SPACE_IN_URI\"; sid:33; gid: 119; rev: 1; metadata: rule-type preproc ; classtype:unknown; )\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 22\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert ( msg:\"DECODE_TCP_DGRAM_LT_TCPHDR\"; sid:45; gid:116; rev:1; metadata:rule-type decode;classtype:protocol-command-decode; )\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 24\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert ( msg:\"DECODE_TCP_INVALID_OFFSET\"; sid:46; gid:116; rev:1; metadata:rule-type decode; reference:cve,2004-0816; classtype:bad-unknown; )\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 26\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert ( msg:\"DECODE_TCP_LARGE_OFFSET\"; sid:47; gid:116; rev:1; metadata:rule-type decode; classtype:bad-unknown; )\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 28\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert ( msg:\"DECODE_TCPOPT_BADLEN\"; sid:54; gid:116; rev:1; metadata:rule-type decode; reference:bugtraq,14811; classtype:protocol-command-decode; )\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 30\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert ( msg:\"DECODE_TCPOPT_TRUNCATED\"; sid:55; gid:116; rev:1; metadata:rule-type decode; classtype:protocol-command-decode; )\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 32\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert ( msg:\"DECODE_TCPOPT_TTCP\"; sid:56; gid:116; rev:1; metadata:rule-type decode; classtype:protocol-command-decode; )\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 34\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert ( msg:\"DECODE_TCPOPT_OBSOLETE\"; sid:57; gid:116; rev:1; metadata:rule-type decode; classtype:protocol-command-decode; )\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 36\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert ( msg:\"DECODE_TCPOPT_EXPERIMENT\"; sid:58; gid:116; rev:1; metadata:rule-type decode; classtype:protocol-command-decode; )\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 38\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature \"alert ( msg:\"DECODE_TCPOPT_WSCALE_INVALID\"; sid:59; gid:116; rev:1; metadata:rule-type decode; classtype:protocol-command-decode; )\" from file /var/folders/mc/ty8hg88x2d1fw9x3zx2qz9f80000gn/T/tmpADsHTB/file.rules at line 40\n30/8/2015 -- 18:41:36 - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature 
```

**Comment by regit** [comment]
Yes so it works :)
If you use latest suricata git then you would have a list of errors instead. But that would not change the amount of errors.

**Comment by Drewshg312** [comment]
ok but what should I do now?

**Comment by regit** [comment]
Ignore errors :/ or fix suricata code to support all VRT rules.

**Comment by Drewshg312** [comment]
Ic)) So basically you saying that Validity problem is just because of the suricata errors with VRT rules?

**Comment by regit** [comment]
Yes.

**Comment by Drewshg312** [comment]
Gotcha!!! But why would you suggest to use the latest git version of suricata?

**Comment by regit** [comment]
It will just improve the output of errors in scirius, a list instead of a single HUGE message.

**Comment by Drewshg312** [comment]
I get it! Thanx for all that explanations... So I believe suricata developers aware of that problem with VRT...
