### ISSUE TITLE
Elasticsearch 2.0.0 + Kibana 4.2

### ISSUE THREAD

**Issue by mghiglieri** [StamusNetworks/scirius#56]
Hi,

it seems that scirius rule management isn't compatible with Elasticsearch 2.0.0. I attached the error message of Elasticsearch. Some googling has brought up that facets was deprecated.

```
uery]]]; nested: SearchParseException[failed to parse search source [
{
  "facets": {

    "ETOpenRuleset": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "864s"
      },
      "global": true,
      "facet_filter": {
        "fquery": {
          "query": {
            "filtered": {
              "query": {
                "query_string": {
                  "query": "event_type:alert AND host.raw:ETOpenRuleset "
                }
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "range": {
                        "@timestamp": {
                          "from": 1446972805526,
                          "to": "now"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]];
Caused by: SearchParseException[failed to parse search source [
{
  "facets": {

    "ETOpenRuleset": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "864s"
      },
      "global": true,
      "facet_filter": {
        "fquery": {
          "query": {
            "filtered": {
              "query": {
                "query_string": {
                  "query": "event_type:alert AND host.raw:ETOpenRuleset "
                }
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "range": {
                        "@timestamp": {
                          "from": 1446972805526,
                          "to": "now"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]];
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:860)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:663)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:632)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:374)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: SearchParseException[failed to parse search source. unknown search element [facets]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:841)
	... 10 more
[2015-11-09 09:53:26,089][DEBUG][action.search.type       ] [Armadillo] All shards failed for phase: [query]
RemoteTransportException[[Armadillo][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [
{
  "facets": {

    "ETOpenRuleset": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "864s"
      },
      "global": true,
      "facet_filter": {
        "fquery": {
          "query": {
            "filtered": {
              "query": {
                "query_string": {
                  "query": "event_type:alert AND host.raw:ETOpenRuleset "
                }
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "range": {
                        "@timestamp": {
                          "from": 1446972805526,
                          "to": "now"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]];
Caused by: SearchParseException[failed to parse search source [
{
  "facets": {

    "ETOpenRuleset": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "864s"
      },
      "global": true,
      "facet_filter": {
        "fquery": {
          "query": {
            "filtered": {
              "query": {
                "query_string": {
                  "query": "event_type:alert AND host.raw:ETOpenRuleset "
                }
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "range": {
                        "@timestamp": {
                          "from": 1446972805526,
                          "to": "now"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]];
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:860)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:663)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:632)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:374)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: SearchParseException[failed to parse search source. unknown search element [facets]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:841)
	... 10 more
[2015-11-09 09:53:26,091][INFO ][rest.suppressed          ] /logstash-2015.11.08,logstash-2015.11.09/_search Params: {ignore_unavailable=true, index=logstash-2015.11.08,logstash-2015.11.09}
Failed to execute phase [query], all shards failed; shardFailures {[_51jYefST2-53oU31L6xuA][logstash-2015.11.08][0]: RemoteTransportException[[Armadillo][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [
{
  "facets": {

    "ETOpenRuleset": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "864s"
      },
      "global": true,
      "facet_filter": {
        "fquery": {
          "query": {
            "filtered": {
              "query": {
                "query_string": {
                  "query": "event_type:alert AND host.raw:ETOpenRuleset "
                }
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "range": {
                        "@timestamp": {
                          "from": 1446972805526,
                          "to": "now"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]]; }{[_51jYefST2-53oU31L6xuA][logstash-2015.11.09][0]: RemoteTransportException[[Armadillo][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [
{
  "facets": {

    "ETOpenRuleset": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "864s"
      },
      "global": true,
      "facet_filter": {
        "fquery": {
          "query": {
            "filtered": {
              "query": {
                "query_string": {
                  "query": "event_type:alert AND host.raw:ETOpenRuleset "
                }
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "range": {
                        "@timestamp": {
                          "from": 1446972805526,
                          "to": "now"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]]; }{[_51jYefST2-53oU31L6xuA][logstash-2015.11.08][1]: RemoteTransportException[[Armadillo][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [
{
  "facets": {

    "ETOpenRuleset": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "864s"
      },
      "global": true,
      "facet_filter": {
        "fquery": {
          "query": {
            "filtered": {
              "query": {
                "query_string": {
                  "query": "event_type:alert AND host.raw:ETOpenRuleset "
                }
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "range": {
                        "@timestamp": {
                          "from": 1446972805526,
                          "to": "now"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]]; }{[_51jYefST2-53oU31L6xuA][logstash-2015.11.09][1]: RemoteTransportException[[Armadillo][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [
{
  "facets": {

    "ETOpenRuleset": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "864s"
      },
      "global": true,
      "facet_filter": {
        "fquery": {
          "query": {
            "filtered": {
              "query": {
                "query_string": {
                  "query": "event_type:alert AND host.raw:ETOpenRuleset "
                }
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "range": {
                        "@timestamp": {
                          "from": 1446972805526,
                          "to": "now"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]]; }{[_51jYefST2-53oU31L6xuA][logstash-2015.11.08][2]: RemoteTransportException[[Armadillo][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [
{
  "facets": {

    "ETOpenRuleset": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "864s"
      },
      "global": true,
      "facet_filter": {
        "fquery": {
          "query": {
            "filtered": {
              "query": {
                "query_string": {
                  "query": "event_type:alert AND host.raw:ETOpenRuleset "
                }
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "range": {
                        "@timestamp": {
                          "from": 1446972805526,
                          "to": "now"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]]; }{[_51jYefST2-53oU31L6xuA][logstash-2015.11.09][2]: RemoteTransportException[[Armadillo][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [
{
  "facets": {

    "ETOpenRuleset": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "864s"
      },
      "global": true,
      "facet_filter": {
        "fquery": {
          "query": {
            "filtered": {
              "query": {
                "query_string": {
                  "query": "event_type:alert AND host.raw:ETOpenRuleset "
                }
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "range": {
                        "@timestamp": {
                          "from": 1446972805526,
                          "to": "now"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]]; }{[_51jYefST2-53oU31L6xuA][logstash-2015.11.08][3]: RemoteTransportException[[Armadillo][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [
{
  "facets": {

    "ETOpenRuleset": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "864s"
      },
      "global": true,
      "facet_filter": {
        "fquery": {
          "query": {
            "filtered": {
              "query": {
                "query_string": {
                  "query": "event_type:alert AND host.raw:ETOpenRuleset "
                }
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "range": {
                        "@timestamp": {
                          "from": 1446972805526,
                          "to": "now"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]]; }{[_51jYefST2-53oU31L6xuA][logstash-2015.11.09][3]: RemoteTransportException[[Armadillo][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [
{
  "facets": {

    "ETOpenRuleset": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "864s"
      },
      "global": true,
      "facet_filter": {
        "fquery": {
          "query": {
            "filtered": {
              "query": {
                "query_string": {
                  "query": "event_type:alert AND host.raw:ETOpenRuleset "
                }
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "range": {
                        "@timestamp": {
                          "from": 1446972805526,
                          "to": "now"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]]; }{[_51jYefST2-53oU31L6xuA][logstash-2015.11.08][4]: RemoteTransportException[[Armadillo][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [
{
  "facets": {

    "ETOpenRuleset": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "864s"
      },
      "global": true,
      "facet_filter": {
        "fquery": {
          "query": {
            "filtered": {
              "query": {
                "query_string": {
                  "query": "event_type:alert AND host.raw:ETOpenRuleset "
                }
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "range": {
                        "@timestamp": {
                          "from": 1446972805526,
                          "to": "now"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]]; }{[_51jYefST2-53oU31L6xuA][logstash-2015.11.09][4]: RemoteTransportException[[Armadillo][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [
{
  "facets": {

    "ETOpenRuleset": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "864s"
      },
      "global": true,
      "facet_filter": {
        "fquery": {
          "query": {
            "filtered": {
              "query": {
                "query_string": {
                  "query": "event_type:alert AND host.raw:ETOpenRuleset "
                }
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "range": {
                        "@timestamp": {
                          "from": 1446972805526,
                          "to": "now"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]]; }
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:228)
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:174)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:821)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:799)
	at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:361)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: SearchParseException[failed to parse search source. unknown search element [facets]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:841)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:663)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:632)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:374)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	... 3 more
```

**Comment by regit** [comment]
Thanks for the information. I'm gonna look into this. I've migrated my personal ES to 2.0 yesterday so I may come with a fix soon.

**Comment by regit** [comment]
@mghiglieri : It was longer than expected :( but you can now use ES2 with latest master. To do so simply add to your local_settings.py:
```
ELASTICSEARCH_2X = True
```

**Comment by mghiglieri** [comment]
@regit: Thanks. Will check it soon.

**Comment by regit** [comment]
1.1.3 is out and fixes the problem.
