### ISSUE TITLE
migrate fails after upgrade to latest version

### ISSUE THREAD

**Issue by Eagleman7** [StamusNetworks/scirius#87]
python manage.py migrate
-------------------------------
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/lib/python2.7/site-packages/django/db/migrations/loader.py", line 308, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/loader.py", line 291, in _reraise_missing_dependency
    raise exc
django.db.migrations.graph.NodeNotFoundError: Migration rules.0052_useraction_user dependencies reference nonexistent parent node (u'rules', u'0051_auto_20161207_0758')

**Comment by regit** [comment]
@Eagleman7 please update your git tree and retry. I've just pushed the missing patch.

**Comment by Eagleman7** [comment]
liberty prime, back online:

Operations to perform:
  Synchronize unmigrated apps: staticfiles, dbbackup, messages, django_tables2, bootstrap3
  Apply all migrations: sessions, admin, suricata, auth, rules, contenttypes, accounts
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying rules.0050_auto_20161128_2110... OK
  Applying rules.0051_auto_20161207_0758... OK
  Applying rules.0052_useraction_user... OK
